services:
  tax-id-api:
    build: .
    container_name: tax-id-api
    ports:
      - "8000:8000"
    volumes:
      - ./data.csv:/app/data.csv
      - ./.env:/app/.env
    deploy:
      resources:
        limits:
          memory: 1G # data.csv > 300MB
    restart: always
