services:
  tax-id-api:
    build: .
    container_name: tax-id-api
    ports:
      - "8092:8092"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    deploy:
      resources:
        limits:
          memory: 1G # data.csv > 300MB
    restart: always
